#!/bin/bash

# Source version
name=klusters
version=1.6.4

# Package versions
release_ubuntu=ubuntu1
release_fedora=0.fc15
release_opensuse=0.suse114

# Tarball name
tarball=${name}_$version.tar.gz

# Architecture names and full package names (all current versions)
arch_ubuntu_32=i386
arch_ubuntu_64=amd64
arch_fedora_32=i686
arch_fedora_64=x86_64
arch_opensuse_32=i586
arch_opensuse_64=x86_64
package_ubuntu_32=${name}_$version-${release_ubuntu}_$arch_ubuntu_32.deb
package_ubuntu_64=${name}_$version-${release_ubuntu}_$arch_ubuntu_64.deb
package_fedora_32=${name}-$version-${release_fedora}.$arch_fedora_32.rpm
package_fedora_64=${name}-$version-${release_fedora}.$arch_fedora_64.rpm
package_opensuse_32=${name}-$version-${release_opensuse}.$arch_opensuse_32.rpm
package_opensuse_64=${name}-$version-${release_opensuse}.$arch_opensuse_64.rpm

# Architecture names and full package names (current versions for this architecture only)
if [ -z "$(uname -a | grep x86_64)" ]
then
	arch_ubuntu=$arch_ubuntu_32
	arch_fedora=$arch_fedora_32
	arch_opensuse=$arch_opensuse_32
	package_ubuntu=$package_ubuntu_32
	package_fedora=$package_fedora_32
	package_opensuse=$package_opensuse_32
else
	arch_ubuntu=$arch_ubuntu_64
	arch_fedora=$arch_fedora_64
	arch_opensuse=$arch_opensuse_64
	package_ubuntu=$package_ubuntu_64
	package_fedora=$package_fedora_64
	package_opensuse=$package_opensuse_64
fi

# Website
source=http://klusters.sourceforge.net

